services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=marketplace_db'
      - 'POSTGRES_PASSWORD=deimer.tauru'
      - 'POSTGRES_USER=deimer'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: