spring.profiles.active=dev
spring.application.name=marketplace


server.servlet.context-path=/api


# Postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.hibernate.ddl-auto=none
