spring.application.name=marketplace


#spring data jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=deimer
spring.datasource.password=deimer.tauru

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true