

#spring data jpa
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:marketplace_db}
spring.datasource.username=${DB_USER:deimer}
spring.datasource.password=${DB_PASSWORD:deimer.tauru}

spring.docker.compose.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#aws
aws.secret.key=${ACCESS_KEY_ID}
aws.access.key=${SECRET_ACCESS_KEY}
aws.region=${REGION}
#cognito user pool
aws.cognito.clientId=${COGNITO_CLIENT_ID}
aws.cognito.userPoolId=${COGNITO_USER_POOL_ID}
aws.cognito.region=${REGION}
aws.cognito.connectionTimeout=2000
aws.cognito.readTimeout=2000
aws.cognito.identityPoolUrl=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
aws.cognito.jwk=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
aws.cognito.issuer=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

# Admin inicial del sistema
app.admin.email=${EMAIL_ADMIN:deimerhdz21@gmail.com}
app.admin.name=${NAME_ADMIN:Admin}
app.admin.lastName=${LASTNAME_ADMIN:TauruPro}
app.admin.password=${PASSWORD_ADMIN:Admin@2024!}

