server.port=${PORT:8080}
#spring data jpa
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&channel_binding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.docker.compose.enabled=false

#aws
aws.secret.key=${ACCESS_KEY_ID}
aws.access.key=${SECRET_ACCESS_KEY}
aws.region=${REGION}

aws.bucket=${BUCKET_NAME:dev-ecommerce-mvp-general-files}

#cognito user pool
aws.cognito.clientId=${COGNITO_CLIENT_ID}
aws.cognito.userPoolId=${COGNITO_USER_POOL_ID}
aws.cognito.connectionTimeout=2000
aws.cognito.readTimeout=2000
aws.cognito.identityPoolUrl=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
aws.cognito.jwk=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
aws.cognito.issuer=https://cognito-idp.${REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}


# Admin inicial del sistema
app.admin.email=${EMAIL_ADMIN}
app.admin.name=${NAME_ADMIN}
app.admin.lastName=${LASTNAME_ADMIN}
app.admin.password=${PASSWORD_ADMIN}